language: node_js
node_js: stable
cache: yarn
before_install:
  - npm install yarn 
install:
  - yarn install --ignore-engines
script:
  - yarn build
after_script:
  - cd ./dist
  - git init
  - git config user.name "NoManReady"
  - git config user.email "453421041@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
    - dev
env:
  global:
    - GH_REF: github.com/NoManReady/shuyue.git
notifications:
  email:
    recipients:
      - 453421041@qq.com
    on_success: always
    on_failure: always
